# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=advancedmachinery
archives_base_name=advanced-machinery
mod_version=0.8.1
mod_group_id=com.advancedmachinery
mod_name=Advanced Machinery
mod_license=MIT
mod_authors=Franchino961
mod_description=An addon for Actually Additions adding advanced multi-block machinery.

# Minecraft Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge Properties
neo_version=21.1.223
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Actually Additions
# File ID CurseMaven: 5819948 (versione 1.3.1 per NeoForge 1.21.1)
actually_additions_version=1.3.1
actually_additions_file_id=5819948

# JEI
jei_version=19.21.0.247